default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

production:
  <<: *default
  adapter: sqlite3
  production:
  url: <%= ENV['DATABASE_URL'] %>
  database: db/development.sqlite3
